name: Post

on:
  push:
    branches:
      - main


jobs:
  images:
    name: images
    runs-on: ubuntu-latest
    steps:
    - name: print hello world
      run: echo "hello world"

  trigger:
    needs: [images]
    name: trigger another job in another repo
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: stolostron/cluster-proxy
          event-type: changes
          client-payload: '{"from": "trigger"}'
